name: 'Azure CLI Wrapper Action'
description: 'Purge containers from your the Azure Container Registry'
author: 'Plabick'
branding:
  icon: 'check-circle'  
  color: 'blue'
inputs:
  username: 
    description: 'Azure Service Principal Username'
    required: false
  tenant: 
    description: 'Azure Service Principal Tenant'
    required: false
  password:
    description: 'Azure Service Principal Tennant ID'
    required: false
  command:
    description: "The command to run, starting with `az`"
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.username }}
    - ${{ inputs.tenant }}
    - ${{ inputs.password }}
    - ${{ inputs.command }}

