name: Test Action
on:
  workflow_dispatch:
  push:
    branches: [ master ]
jobs:
  update-readme:
    runs-on: [ubuntu-latest]
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2

    - name: Start MyContainerGroup
      uses: Plabick/ACR-Container-Purge-Action@master
      with:
        registry: ${{ secrets.registry }}
        username: ${{ secrets.service-principal-username }}
        tenant: ${{ secrets.service-principal-tenant }}
        password: ${{ secrets.SERVICE_PRINCIPAL_TOKEN }}
        command: 'az container start --name MyContainerGroup --resource-group MyResourceGroup'
